CREATE DATABASE SEKOLAH1;
USE SEKOLAH1;
CREATE TABLE SISWA(
NIS VARCHAR(10) PRIMARY KEY NOT NULL,
NAMA VARCHAR(50) NOT NULL,
ALAMAT TEXT NOT NULL,
KELAS VARCHAR(10) NOT NULL,
JENIS_KELAMIN VARCHAR(1) NOT NULL,
NO_HP VARCHAR(15) NOT NULL,
KENDARAAN VARCHAR(20) NULL,
TANGGAL_LAHIR DATE NOT NULL
);

CREATE TABLE NILAI(
KODE_MAPEL INT NOT NULL PRIMARY KEY,
NIS VARCHAR(20) NOT NULL,
NAMA_MAPEL VARCHAR(20) NOT NULL,
NILAI DOUBLE NOT NULL,
KETERANGAN TEXT
);

DROP TABLE NILAI;

CREATE TABLE MAPEL(
KODE_MAPEL INT NOT NULL PRIMARY KEY,
NAMA_MAPEL VARCHAR(50) NOT NULL,
KETERANGAN TEXT
);

CREATE TABLE GURU(
NIP VARCHAR (20) PRIMARY KEY NOT NULL,
NAMA VARCHAR (50) NOT NULL,
KODE_MAPEL INT NOT NULL,
JENIS_KELAMIN VARCHAR(1),
ALAMAT TEXT NOT NULL,
KENDARAAN VARCHAR (20) NULL
);

CREATE TABLE JABATAN(
NOREG_JABATAN INT PRIMARY KEY,
NAMA_JABATAN VARCHAR(50) NOT NULL,
KETERANGAN TEXT NULL
);

CREATE TABLE GURU_MENJABAT(
NIP VARCHAR(20) NOT NULL,
NORENG_JABATAN INT NOT NULL
);


DESC NILAI;
DESC MAPEL;
DESC SISWA;
DESC GURU;
DESC JABATAN;
DESC GURU_MENJABAT;

DROP TABLE NILAI;

INSERT INTO SISWA
VALUES
(101,"MOGI","JAKARTA BARAT", "XI TEL 10","L",08567272661,"MOBIL",20020921),
(102,"MOCI","JAKARTA SELATAN", "XI TEL 10","L",08873625222,"MOBIL",20030131),
(103,"MOZA","JAKARTA BARAT", "XI TEL 10","P",09213738277,"",20021008);

INSERT INTO NILAI
VALUES
("1","101","BASIS DATA","80.7","KOMPETEN"),
("2","102","PEMOGRAMAN WEB","90","KOMPETEN"),
("3","101","PEMOGRAMAN DASAR","74","TIDAK KOMPETEN");

INSERT INTO MAPEL
VALUES
(1,"BASIS DATA","BELAJAR PERANCANGAN DAN PEMBUATAN DATABASE"),
(2,"PEMOGRAMAN WEB","BELAJAR PEMBUATAN WEBSITE"),
(3,"PEMOGRAMAN DASAR","BELAJAR DASAR - DASAR PEMOGRAMAN"),
(4,"JARIGAN DASAR","BELAJAR DASAR - DASAR JARINGAN"),
(5, "PEMOGRAMAN PERANGKAT BERGERAK","BELAJAR APLIKASI ANDROID");

INSERT INTO GURU
VALUES
("G01","MOGI","1","L","JAKARTA SELATAN","MOTOR"),
("G02","MOCI","2","L","JAKARTA BARAT","MOTOR"),
("G03","MOZA","3","L","TANGERANG","MOTOR"),
("G04","CATTY","4","P","JAKARTA BARAT","BUSWAY"),
("G05","OREN","5","L","JAKARTA BARAT","MOTOR");

INSERT INTO JABATAN
VALUES
(121,"KEPALA SEKOLAH",""),
(122,"WAKIL KEPALA SEKOLAH","BIDANG KURIKULUM"),
(123,"KEPALA ADMINISTRASI","BIDANG KEUANGAN");

INSERT INTO GURU_MENJABAT
VALUES
("G01",121),
("604",123),
("602",122);

SELECT*FROM GURU;
SELECT*FROM JABATAN;
SELECT*FROM GURU_MENJABAT;
SELECT*FROM NILAI;
SELECT*FROM MAPEL;
SELECT*FROM SISWA;

SELECT SISWA.NAMA,SISWA.KELAS,MAPEL.NAMA_MAPEL,NILAI.NILAI,NILAI.KETERANGAN
FROM SISWA,NILAI,MAPEL
WHERE SISWA.NIS = NILAI.NIS AND NILAI.KODE_MAPEL = MAPEL.KODE_MAPEL;

SELECT SISWA.NAMA,SISWA.KELAS,NILAI.KODE_MAPEL,NILAI.NILAI,NILAI.KETERANGAN
FROM SISWA,NILAI
WHERE NILAI.NIS = SISWA.NIS;

SELECT SISWA.NAMA, SISWA.KELAS, MAPEL.NAMA_MAPEL, NILAI.NILAI, NILAI.KETERANGAN
FROM SISWA, MAPEL, NILAI
WHERE NILAI.NIS = SISWA.NIS = MAPEL.NAMA_MAPEL;

SELECT NILAI.NIS, MAPEL.NAMA_MAPEL, NILAI.NILAI, NILAI.KETERANGAN
FROM NILAI, MAPEL
WHERE NILAI.NAMA_MAPEL = MAPEL.NAMA_MAPEL;

SELECT SISWA.NIS, SISWA.NAMA, SISWA.KELAS, NILAI.KODE_MAPEL,NILAI.NILAI
FROM SISWA, NILAI
WHERE SISWA.NIS = NILAI.NIS;

#UPDATE : MELAKUKAN PERUBAHAN DATA
#UPDATE SET ATT1 = DATABARUNYA, ATT2 = DATABARUNYA WHERE PRIMARYKEY = DATA
UPDATE SISWA SET NAMA = "CHRIS", ALAMAT = "TANGERANG" WHERE NIS = "101";

#SELECT

#1. MENAMPILKAN SEMUA DATA
#SELECT * FROM NAMATABLENYA;

SELECT * FROM SISWA;

#2. MENAMPILKAN SEMUA DATA DENGAN KRITERIA TERTENTU (WHERE)
#SELECT * FROM NAMATABELNYA WHERE ATT_KRITERIA = DATANYA;
SELECT * FROM SISWA WHERE NAMA = "CHRISTIAN";

#3. MENAMPILKAN BEBERAPA DATA
SELECT NAMA, ALAMAT, JENIS_KELAMIN FROM SISWA;
SELECT NAMA, ALAMAT, JENIS_KELAMIN FROM SISWA WHERE KENDARAAN = "MOTOR";

#DELETE
#1. DELETE YANG DIGUNAKAN UNTUK MENGHAPUS 1 BARIS DATA
DELETE FROM SISWA WHERE NIS = "102";
#2. DELETE SEMUA DATA
DELETE FROM SISWA;
TRUNCATE TABLE SISWA;

#JOIN
#Join untuk memanggil table siswa dan nilai dengan sama
SELECT * from Siswa INNER JOIN nilai on nilai.NIS = Siswa.NIS;

#Join untuk memanggil nilai yang sama tetapi Siswa menjadi reverensi sehingga table siswa memunculkan seluruh isi tabel siswa
SELECT * from Siswa  LEFT JOIN nilai on nilai.NIS = Siswa.NIS;

#Join untuk menampilkan seluruh tabel dibagian nilai terlebih dahulu lalu tabel siswa mengikuti tabel nilai
SELECT * from Siswa  RIGHT JOIN nilai on nilai.NIS = Siswa.NIS;