CREATE DATABASE SEKOLAH2;
USE SEKOLAH2;

CREATE TABLE SISWA1(
NIS INT PRIMARY KEY NOT NULL,
NAMA VARCHAR(20) NOT NULL,
KELAS VARCHAR(10) NOT NULL
);

DROP TABLE SISWA1;
DROP TABLE MAPEL1;
DROP TABLE NILAI1;

CREATE TABLE MAPEL1(
KODE_MAPEL VARCHAR(2) NOT NULL PRIMARY KEY,
NAMA_MAPEL VARCHAR (30)
);

#CARA PEMBUATAN FK PERTAMA NAMA DEFAULT
CREATE TABLE NILAI1(
NIS INT NOT NULL,
KODE_MAPEL VARCHAR(2) NOT NULL,
NILAI INT,
FOREIGN KEY (NIS) REFERENCES SISWA1(NIS)
);

DROP TABLE NILAI1;

#CARA PEMBUATAN FK PERTAMA NAMA SENDIRI
CREATE TABLE NILAI1(
NIS INT NOT NULL,
KODE_MAPEL VARCHAR(2) NOT NULL,
NILAI INT,
CONSTRAINT INFOFOREIGNKEYKODE_MAPEL
FOREIGN KEY (KODE_MAPEL) REFERENCES MAPEL1(KODE_MAPEL),
CONSTRAINT INFOFOREIGNKEYNIS
FOREIGN KEY (NIS) REFERENCES SISWA1(NIS)
);

#MENGHAPUS FOREIGN KEY 
ALTER TABLE NILAI1 DROP FOREIGN KEY INFOFOREIGNKEYNIS;

#MEMBUAT FOREIGN KEY SETELAH TABLE NAMA SENDIRI
ALTER TABLE NILAI1 ADD CONSTRAINT INFOFOREIGNKEYNIS
FOREIGN KEY (NIS) REFERENCES SISWA1(NIS);

#MEMBUAT FOREIGN KEY SETELAH TABLE NAMA SENDIRI
ALTER TABLE NILAI1 ADD FOREIGN KEY (NIS) REFERENCES SISWA1(NIS);