#INI KOMENTTAR 1 BARIS
/*INI
KOMENTAR LEBIH DARI
SATU BARIS*/

#DDL (DATA DEFINITION LANGUAGE)
#CREATE, ALTER, DROP
#CREATE - MEMBUAT DATABASE DAN TABEL
#MEMBUAT DATABASE
#CREATE DATABASE NAMA_DATABASENYA;

#MENGGUNAKAN DATABASE
#USE NAMA_DATABASENYA;

#MEMBUAT TABEL
#CREATE TABLE NAMA_TABELNYA (NAMA_ATT TIPEDATANYA CONSTRAINTNYA);

#MELIHAT STRUKTUR TABEL
/*---------------------------------*/

CREATE DATABASE TOKO;
USE TOKO;
CREATE TABLE KARYAWAN(
ID_KARYAWAN INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NAMA_KARYAWAN VARCHAR(50) NOT NULL,
JENIS_KARYAWAN VARCHAR(20) NOT NULL,
STATUS_PERNIKAHAN VARCHAR (20) NOT NULL,
ALAMAT TEXT NOT NULL,
KENDARAAN VARCHAR(20) NULL
);
DESC KARYAWAN;

/*----------------------*/

#DDL : ALTER
#ALTER DIGUNAKAN UNTUK MENGODIFIKASI STRUKTUR TABEL

# 1 ALTER UNTUK MENAMBAH ATRIBUT/COLUMMN
#ALTER TABLE NAMA_TABLENYA ADD COLUMN ATT_BARU TIPEDATA NULL/NOTNULL;
ALTER TABLE KARYAWAN ADD COLUMN JUMLAH_KELUARGA INT NULL;
ALTER TABLE KARYAWAN ADD COLUMN GAJI INT NOT NULL AFTER ALAMAT;
DESC KARYAWAN;

#2. ALTER UNTUK MENGHAPUS ATT/KOLOM
#ALTER TABLE NAMA_TABLENYA DROP COLUMN ATT_YANG DI HAPUS
ALTER TABLE KARYAWAN DROP COLUMN GAJI_KARYAWAN;

#3. ALTER UNTUK MENGUBAH STRUKTUR ATRIBUT
#ALTER TABLE NAMA_TABELNYA MODIFY ATTYGINDIUBAH TIPEDATABARU;
ALTER TABLE KARYAWAN MODIFY STATUS_PERNIKAHAN VARCHAR(50) NULL;

#4. ALTER UNTUK MENGUBAH NAMA ATRIBUT/KOLOM
#ALTER TABLE NAMA_TABELNYA CHANGE ATTLAMA ATTBARU TIPEDATA;
ALTER TABLE KARYAWAN CHANGE GAJI GAJI_KARYAWAN INT NOT NULL;

#5. ALTER UNTUK MENGUBAH NAMA TABEL
#ALTER TABLE NAMA_TABELLAMANYA RENAME TO NAMA_TABELBARUNYA;
ALTER TABLE KARYAWAN RENAME TO PEGAWAI;

/*---------------------------------------------------*/

#DDL : DROP

#DROP UNTUK MENGHAPUS TABEL DAN DATABASE

#1. TABLE DIHAPUS = DATA DIHAPUS

#2. DATABASE DIHAPUS = TABLE DAN DATA DIHAPUS

#DROP UNTUK MENGAHAPUS TABLE 
#DROP TABLE NAMA TABELNYA
DROP TABLE P;

#DROP UNTUK MENGHAPUS DATABASE
#DROP DATABASE NAMADATABASENYA;
DROP DATABASE TOKO;

/*-------------------------------------------------------*/
#DML : DATA MANIPULATION LANGUAGE
#DML : INSERT, SELECT, UPDATE, dan DELETE
#INSERT : MEMASUKAN/MENAMBAH DATA KE DALAM TABEL

#1. MEMASUKAN SEMUA DATA KEDALAM TABEL
#INSERT INTO NAMATABEL VALUES (BARISDATA1),(BARISDATA2), (DST);
INSERT INTO KARYAWAN VALUES
(101, "Tian JS", "L", "Lajang", "Jakarta Selatan", "Mobil"),
(102, "Vendra AW", "L", "Menikah", "Tangerang", "");

#2 MEMASUKAN BEBERAPA DATA
#INSERT INTO NAMATABEL (NAMAATT) VAULES (BARISDATA1), (DST);

INSERT INTO KARYAWAN 
(ID_KARYAWAN, NAMA_KARYAWAN, JENIS_KARYAWAN, STATUS_PERNIKAHAN, ALAMAT)
VALUES
(103, "FAUZAN", "OB", "DUDA", "TANGERANG");

#3. MENGECEK ERROR
#INSERT IGNORE INTO NAMATABLE VALUES (BARISDATA1), (DST);
INSERT IGNORE INTO KARYAWAN VALUES
(105,"TIAN JS", "L", "LAJANG", "JAKARTA SELATAN", "MOBIL"),
(106, "VENDRA AW", "L", "MENIIKAH", "TANGERANG","");

SELECT * FROM KARYAWAN;

DESC KARYAWAN;

/*JENIS ERROR
1. NO DATABASE SELECTED : DATABASE BELUM DI PILIH (USE NAMADATABASE)
2. TABLE DOESN'T EXIST : TABELNYA TIDAK ADA (CEK DATABASE / TABELNYA)
3. UNKNOWN DATABASE : DATABASE TIDAK ADA (CEK DATABASE / SCHEMAS)
4. COLUMN COUNT DOESN'T MATCH : JUMLAH DATA YANG DIMASUKAN TIDAK SAMA DENGAN JUMLAH ATT (CEK JUMLAH ATT DAN JUMLAH DATA YANG DIMASUKAN)

/*-----------------------------------------------------------------*/
#DML: SELECT
#SELECT : DIGUNAKAN UNTUK MENAMPILKAN DATA
#1. DIGUNAKAN UNTUK MENAMPILKAN SEMUA DATA DIDALAM TABEL
#SELECT * FROM NAMATABELNYA;