SELECT 
	ID_KENDARAAN,MEREK,MODEL,HARGA_SEWA_PERHARI
FROM
	KENDARAAN
WHERE
	MEREK = 'Toyota';
    
SELECT
	ID_PEGAWAI, NAMA_CABANG,NAMA_LENGKAP,JENIS_KELAMIN,JABATAN
FROM
	PEGAWAI
WHERE 
	JENIS_KELAMIN = 'Perempuan' AND JABATAN = 'Manager';

SELECT
	JENIS_KELAMIN,JABATAN,COUNT(JENIS_KELAMIN) AS JUMLAH_PEGAWAI
FROM
	PEGAWAI
WHERE
	JENIS_KELAMIN = 'Laki-laki' AND JABATAN = 'Staff';
    
SELECT
	METODE_BAYAR, COUNT(METODE_BAYAR) AS KUANTITAS
FROM
	PEMBAYARAN
GROUP BY
	METODE_BAYAR
ORDER BY
	KUANTITAS DESC;

SELECT P.NAMA_PELANGGAN, COUNT(S.ID_PELANGGAN) AS JUMLAH_TRANSAKSI, SUM(S.TOTAL_BIAYA) AS JUMLAH_PENGELUARAN
FROM PENYEWAAN S
JOIN PELANGGAN P
ON P.ID_PELANGGAN = S.ID_PELANGGAN
GROUP BY P.NAMA_PELANGGAN
ORDER BY JUMLAH_PENGELUARAN DESC; 

SELECT P.NAMA_LENGKAP, COUNT(S.ID_PEGAWAI) AS JUMLAH_MENANGANI_TRANSAKSI
FROM PENYEWAAN S
JOIN PEGAWAI P
ON P.ID_PEGAWAI = S.ID_PEGAWAI
GROUP BY P.NAMA_LENGKAP
ORDER BY JUMLAH_MENANGANI_TRANSAKSI DESC; 




#contoh
SELECT 
    id_kendaraan, 
    COUNT(id_kendaraan) AS jumlah_pinjam
FROM 
    Penyewaan
GROUP BY 
    id_kendaraan
ORDER BY 
    jumlah_pinjam DESC;
    
SELECT 
    METODE_BAYAR, 
    COUNT(METODE_BAYAR) AS jumlah_metode_bayar
FROM 
    Pembayaran
WHERE
	METODE_BAYAR = 'Transfer';
    
SELECT * FROM Pembayaran;
    
SELECT 
	ID_KENDARAAN,MEREK,MODEL,MODEL,HARGA_SEWA_PERHARI
FROM
	KENDARAAN
WHERE
	STATUS_KENDARAAN = 'Tersedia';
    
SELECT * FROM KENDARAAN;

SELECT ID_PELANGGAN, TOTAL_BIAYA
FROM PENYEWAAN
WHERE TOTAL_BIAYA > (
	SELECT AVG(TOTAL_BIAYA)
    FROM PENYEWAAN);
    
SELECT P.NAMA_PELANGGAN,S.ID_SEWA,S.TANGGAL_SEWA,S.TOTAL_BIAYA
FROM PELANGGAN P
JOIN PENYEWAAN S
ON P.ID_PELANGGAN = S.ID_PELANGGAN;

SELECT ID_PELANGGAN, TOTAL_BIAYA, AVG(TOTAL_BIAYA) AS RATA_TOTAL_BIAYA
FROM PENYEWAAN
WHERE TOTAL_BIAYA > RATA_TOTAL_BIAYA
GROUP BY ID_PELANGGAN;