DROP DATABASE rentalskuy;
#MEMBUAT DATABASE RENTALSKUY
CREATE DATABASE RENTALSKUY;
USE RENTALSKUY;

##PENGERJAAN BAGIAN JEFRI##
#MEMBUAT ENTITY PELANGGAN DAN ATRIBUTNYA
CREATE TABLE PELANGGAN(
ID_PELANGGAN VARCHAR(10) PRIMARY KEY NOT NULL,
NAMA_PELANGGAN VARCHAR(50) NOT NULL,
ALAMAT VARCHAR(20) NOT NULL,
NO_HP VARCHAR(15) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TANGGAL_LAHIR DATE NOT NULL,
JENIS_KELAMIN VARCHAR(20) NOT NULL,
STATUS_KEANGGOTAAN VARCHAR(20) NOT NULL,
TOTAL_PENYEWAAN INT NULL
);

#MEMBUAT ENTITY KENDARAAN DAN ATRIBUTNYA
CREATE TABLE KENDARAAN(
ID_KENDARAAN VARCHAR(10) PRIMARY KEY NOT NULL,
NOMOR_POLISI INT NOT NULL,
MEREK VARCHAR(20) NOT NULL,
MODEL VARCHAR(20) NOT NULL,
TIPE_VARIAN_MODEL VARCHAR(20) NOT NULL,
TAHUN_PEMBUATAN DATE NOT NULL,
WARNA VARCHAR(20) NOT NULL,
KAPASITAS_PENUMPANG INT NOT NULL,
JENSI_KENDARAAN VARCHAR(20) NOT NULL,
TRANSMISI VARCHAR(20) NOT NULL,
BAHAN_BAKAR VARCHAR(20) NOT NULL,
HARGA_SEWA_PERHARI 	INT NOT NULL,
STATUS_KENDARAAN VARCHAR(20) NOT NULL 
);

#MEMBUAT ENTITY KOORDINAT DAN ATRIBUTNYA
CREATE TABLE KOORDINAT(
ID_KENDARAAN VARCHAR(10) NOT NULL,
LONGITUDE VARCHAR(50) NOT NULL,
LATITUDE VARCHAR(50) NOT NULL,
CONSTRAINT FK_ID_KENDARAAN
FOREIGN KEY (ID_KENDARAAN) REFERENCES KENDARAAN(ID_KENDARAAN)
);

#MEMBUAT ENTITY CABANG DAN ATRIBUTNYA
CREATE TABLE CABANG(
NAMA_CABANG VARCHAR(20) PRIMARY KEY NOT NULL,
ALAMAT VARCHAR(20) NOT NULL,
NOMOR_TELEPON INT NOT NULL,
JUMLAH_PEGAWAI INT NOT NULL,
LIST_KENDARAAN_DISEWAKAN VARCHAR(50)
);


##PEKERJAAN BAGIAN SATRIA##
#MEMBUAT ENTITY PEGAWAI DAN ATRIBUTNYA
CREATE TABLE PEGAWAI(
ID_PEGAWAI VARCHAR(10) PRIMARY KEY NOT NULL,
NAMA_CABANG VARCHAR(50) NOT NULL,
NAMA_LENGKAP VARCHAR(100) NOT NULL,
NO_TELP INT NOT NULL,
EMAIL VARCHAR(50) UNIQUE NOT NULL,
TANGGAL_LAHIR DATE NOT NULL,
JENIS_KELAMIN VARCHAR(10) NOT NULL,
JABATAN VARCHAR(20) NOT NULL,
CONSTRAINT FK_NAMA_CABANG
FOREIGN KEY (NAMA_CABANG) REFERENCES CABANG(NAMA_CABANG)
);

##PEKERJAAN BAGIAN GADING##
##MEMBUAT TABLE PENYEWAAN
CREATE TABLE PENYEWAAN (
ID_SEWA VARCHAR(10) PRIMARY KEY,
ID_PELANGGAN VARCHAR(10) NOT NULL,
ID_KENDARAAN VARCHAR(10) NOT NULL,
ID_PEGAWAI VARCHAR(10) NOT NULL,
TANGGAL_SEWA DATE NOT NULL,
TANGGAL_KEMBALI DATE NOT NULL,
TOTAL_BIAYA INT NOT NULL,
STATUS_SEWA VARCHAR(20) NOT NULL,
CONSTRAINT FK_PELANGGAN_SEWA
FOREIGN KEY (ID_PELANGGAN) REFERENCES PELANGGAN(ID_PELANGGAN),
CONSTRAINT FK_KENDARAAN_SEWA
FOREIGN KEY (ID_KENDARAAN) REFERENCES KENDARAAN(ID_KENDARAAN),
CONSTRAINT FK_PEGAWAI_SEWA
FOREIGN KEY (ID_PEGAWAI) REFERENCES PEGAWAI(ID_PEGAWAI)
);

##PEKERJAAN BAGIAN LINDU##
#MEMBUAT ENTITY PEMBAYARAN DAN ATRIBUTNYA
CREATE TABLE PEMBAYARAN(
ID_BAYAR VARCHAR(10) PRIMARY KEY NOT NULL,
ID_SEWA VARCHAR(10) NOT NULL,
CONSTRAINT FK_ID_SEWA
FOREIGN KEY (ID_SEWA) REFERENCES PENYEWAAN(ID_SEWA),
TANGGAL_SEWA DATE NOT NULL,
METODE_BAYAR VARCHAR(20) NOT NULL,
STATUS_BAYAR VARCHAR(20) NOT NULL
);

#MEMBUAT ENTITY DENDA DAN ATRIBUTNYA
CREATE TABLE DENDA(
ID_BAYAR VARCHAR(10) NOT NULL,
CONSTRAINT FK_ID_BAYAR
FOREIGN KEY (ID_BAYAR) REFERENCES PEMBAYARAN(ID_BAYAR),
TANGGAL_DENDA DATE NOT NULL,
JENIS_DENDA VARCHAR(20) NOT NULL
);
