#membuat entity pelanggan
CREATE DATABASE RENTALSKUY;
USE RENTALSKUY;
CREATE TABLE PELANGGAN(
ID_PELANGGAN INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NAMA_PELANGGAN VARCHAR(50) NOT NULL,
ALAMAT VARCHAR(20) NOT NULL,
NO_HP INT NOT NULL,
EMAIL VARCHAR(20) NOT NULL,
TANGGA_LAHIR DATE NOT NULL,
JENIS_KELAMIN VARCHAR(20) NOT NULL,
STATUS_KEANGGOTAAN VARCHAR(20) NOT NULL,
TOTAL_PENYEWAAN INT NULL
);

CREATE TABLE KENDARAAN(
ID_KENDARAAN INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOMOR_POLISI INT NOT NULL,
MEREK VARCHAR(20) NOT NULL,
MODEL VARCHAR(20) NOT NULL,
TIPE_VARIAN_MODEL VARCHAR(20) NOT NULL,
TAHUN_PEMBUATAN DATE NOT NULL,
WARNA VARCHAR(20) NOT NULL,
KAPASITAS_PENUMPANG INT NOT NULL,
JENSI_KENDARAAN VARCHAR(20) NOT NULL,
TRANSMISI VARCHAR(20) NOT NULL,
BAHAN_BAKAR VARCHAR(20) NOT NULL,
HARGA_SEWA_PERHARI 	INT NOT NULL,
STATUS_KENDARAAN VARCHAR(20) NOT NULL 
);

CREATE TABLE CABANG(
NAMA_CABANG VARCHAR(20) PRIMARY KEY NOT NULL,
ALAMAT VARCHAR(20) NOT NULL,
NOMOR_TELEPON INT NOT NULL,
JUMLAH_PEGAWAI INT NOT NULL,
LIST_KENDARAAN_DISEWAKAN VARCHAR(50)
);

CREATE TABLE KOORDINAT(
ID_KENDARAAN INT NOT NULL,
LONGITUDE VARCHAR(50) NOT NULL,
LATITUDE VARCHAR(50) NOT NULL,
CONSTRAINT FK_ID_KENDARAAN
FOREIGN KEY (ID_KENDARAAN) REFERENCES KENDARAAN(ID_KENDARAAN)
);

